### ISSUE TITLE
when to access lightDOM

### ISSUE THREAD

**Issue by Danny-Engelman** [daviddarnes/storage-form#5] opened 2024-05-13 12:46 UTC
You have to use ``type="module"`` to make the ``connectedCallback`` run **after DOM is parsed**

* That means the code runs late/last.
* That means the code can not be bundled to execute early

``type="module"`` (or "defer" what some also use) is not required if you **make the ``connectedCallback`` wait for its lightDOM to be parsed**

I wrote a blog about the "issue":

[Web Component Developers do not connect with the ``connectedcallback`` yet](https://dev.to/dannyengelman/web-component-developers-do-not-connect-with-the-connectedcallback-yet-4jo7)

**Comment by daviddarnes** [comment] 2024-05-13 12:54
Closing this as it's pretty much a duplicate of this issue you created https://github.com/daviddarnes/storage-form/issues/2

**Closed as completed by daviddarnes** 2024-05-13 12:54 UTC
Labels: bug
